spring:
  application:
    name: CLOUD-CONSUMER-USER-HYSTRIX-RIBBON
server:
  port: 8005
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #注册时使用ip的方式